GET http://localhost:3000/posts

###

POST http://localhost:3000/posts/add
Content-Type: application/json

{
    "title": "Added date",
    "context": "Added date to posts",
    "author": "Emilia"
}

###