GET http://localhost:3000/posts

###

POST http://localhost:3000/posts/add
Content-Type: application/json

{
    "title": "Posting with create",
    "context": "Another test, Tests if it works to create posts with create function",
    "author": "Emilia"
}

###